replicaCount: 2

image:
  repository: ghcr.io/cloudraftio/metrics-app
  pullPolicy: IfNotPresent
  tag: 1.4 

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000
  allowPrivilegeEscalation: false

ingress:
  hosts:
    - host: "" 
      paths:
        - path: /
          pathType: Prefix

service:
  type: ClusterIP
  port: 8080

resources: 
   limits:
     cpu: 100m
     memory: 128Mi
   requests:
     cpu: 100m
     memory: 128Mi

livenessProbe:
  initialDelaySeconds: 15
  httpGet:
    path: /
    port: 8080
readinessProbe:
  initialDelaySeconds: 15 
  httpGet:
    path: /
    port: 8080

autoscaling:
  enabled: false

app:
  sealedPassword: "AgCcnBUr1dYYzLZPtu/d0uvKNojikER9UmFBY9BDFckpYEhDPd4U67K59w3CvSqJT1SIe5lXgPbMhqnrZVg51cbLh5tqSNBJGbp2OGMSxP0qADIBBOeAt0tFOpDC/5tet5HE3zaPdHfvnYETouin1ynuxhm5GIT2PDlsatnR5xfEqz745sdVTSuqj6OPNFG3j+RaR8bzkq8Z4ZpU1CANAQhe8LHivIklgO++Onjy34M4xBm11wDECwFCy5ETdNqA7l0uCBAeaYrPRhBPJ+qY0L8cAS3hGFySxF6t03iFXmQWcxnHt/UYhlae5IkHv7bEq/vDwAz3sTIN4hn/Kp3FpJAO3Pwxai7EGXf6n2/kaEH7PmwV+Hsg+JLmk2fybGJEYtPRYqNngJU65eyEpkmGLe3A8CUHRB24G3g/p0tsLqkWnGhFAs14IbVjibo6VG37I8xkixk2bivCOEkIaPXKbwriPFWstiUViufMRWW46LHNyUBIbTFtYtkxYViK+uYnc8Ptl0xBT4RRqVVLej3qcAOOe7N7Vox1vbs5tCRlVSld8F2D+sHghmwrgUFLK2dwXtJbKUc0BU1I6cPCfJHLznUFdNfFRVukxkjt4RIAhidOjEqINrnM8GWlpQl1UwDL/bf/Fkx5iiMRpSP1vyXKerRfs4MRAQU9m98t1OebK1oTS2kyESw2AfTlkmiB+nIasDvcvgumjyn8Pp+2"

env:
  password: PASSWORD
