replicaCount: 3

image:
  repository: ghcr.io/cloudraftio/metrics-app
  pullPolicy: IfNotPresent
  tag: 1.4 

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000
  allowPrivilegeEscalation: false


service:
  type: ClusterIP
  port: 8080

resources: 
   limits:
     cpu: 100m
     memory: 128Mi
   requests:
     cpu: 100m
     memory: 128Mi

livenessProbe:
  initialDelaySeconds: 15
  httpGet:
    path: /
    port: 8080
readinessProbe:
  initialDelaySeconds: 15 
  httpGet:
    path: /
    port: 8080

autoscaling:
  enabled: false

app:
  sealedPassword: "AgBTsGsHrHOXnr616tzr/+YiqKDgjPnlHeVgZvp8xXuVxIzEHLWNRRTPOrQ5kM43LYx1vzEyi0UOQAX7LbBtAqXe5Y58oztZFrIFEuFJCd22f7I2mBHKMbGjSdwLqSISerowaNFAMCa3GE6K0uyOrcvjN4ktt7xxKT/Sna3BLMD1cXPpVMmCy/jaunvnqwo3V+c8xi+V1pHzUDqPc7IoP9g27Yz+jLdkR/Anu6Wulg4EdmpedmO9CrutBTr0li6CpDpIeRTKV0LdV9K3dClecNiFFrRTli6yt1GaRiS2KlABTo3M6dm+jyShpWKRw1oo6SDb4Rph6CfwHCDqWFD1hl0gjWM1hEnE+e7lnk1P4sbiSz76efMYaL6Y6JdKvL0SvYsCiH7PxUFM4v5cOn0CY88Elu+O6CKZ8wL+FE17iWCVHdtvNDp9lnFIEDPhpPmD3k0ePIzESFdXeYAAUqqgcUvRBDbrINrtu87GrNYDQGME30Zrxj2zaxW4ay6QwHAQC1Bv4QmdCRFtw4S35TR3lIrRrRs9EypA8DOiGo8vNqn4iwRX2KBxZz8fpFB4UKf7aitacz3Q50kLvpJtgsMZxhqfc+F3QZiXYpfcEgEmJvWHJREtXwhK1QIOcLM638bI0eLy62jGr7fPXLvPXtcESzdaJBEAMKQjDDN6NNsillxzifSle1nOiOvlkpKbBHk7fBCzKmSWripHYPOM"

