replicaCount: 2

image:
  repository: ghcr.io/cloudraftio/metrics-app
  pullPolicy: IfNotPresent
  tag: 1.4 

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000
  allowPrivilegeEscalation: false

ingress:
  enabled: false

service:
  type: ClusterIP
  port: 8080

resources: 
   limits:
     cpu: 100m
     memory: 128Mi
   requests:
     cpu: 100m
     memory: 128Mi

livenessProbe:
  initialDelaySeconds: 15
  httpGet:
    path: /
    port: 8080
readinessProbe:
  initialDelaySeconds: 15 
  httpGet:
    path: /
    port: 8080

autoscaling:
  enabled: false

app:
  sealedPassword: "AgC0QRXlqw+TfJB7SCAfgXrdIpL5N4kgMU4/ohdk2lizyOBmJKKNJAI5GFH/BufEtfaoiBKAIISjarklJSVbZ7zZPWo0R2/twRdxtCfpI0AO1oO8BR7iNds1ATKwoPzYhsWjM7CKW4JPGxfINgxf6I1ehAEPVxGqofMclZFfQmCiromwYi5BCM5am0/3EjJo2JuxDuFZl3aghpQCEGFFhn/bboiW2GXZInNKtko2fMI+ubunnlH0AeSCiWFtL0OE87r2olQZRvn5KSVy9bLWxMsU2BpdkvUDrRZisojgb6CVNPHLzKDjNTcBVff1JhNSoXm9Q2EKuHQ8NBnp41LX3DnzZ6/KSYW4/7iSlIb0VwXrC03f1NZ+rM+sLZi8elZLavXbLh4KNoVHPLf37e10qlIkcodw47Gkqyp34UMLs4gdoy34m512RqzgHVlau/HduL5McrnsoyGUhZFkNI9B/GN8/jRJkAHkE44heabqaPYzbaYZ/ZTjOQ+gqFCm/a2+ntrf5O4CNa4QG8go6dv/8sESg4STJbS9vMrrfQhk4Yb/+aA4L7fUbZ9uxSyEj8YuS3eCh6CQ7AZA0/g/VJwT+Gw2rniLTAz5YOpzbQSLcUqPuzsjBf7hUrZjZfKavk3xxTuI5Yxq1x3gmWf26e+Xcb4PpyXpRFOyH++NWGP1EJ0bMs2RwK844o6H03mhr3h/OzbFCMgIlRg4gAD8"
