apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "metrics-app.fullname" . }}-secret
  labels:
    {{- include "metrics-app.labels" . | nindent 4 }}
spec:
  encryptedData:
    PASSWORD: {{ .Values.app.sealedPassword | quote }}
  template:
    metadata:
      name: {{ include "metrics-app.fullname" . }}-secret
      labels:
        {{- include "metrics-app.labels" . | nindent 8 }}
    type: Opaque
